# Site settings
name: pyromakesmusic
title: pyromakesmusic
description: > # this means to ignore newlines until "baseurl:"
  Projects and data analysis by pyromakesmusic.
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://pyromakesmusic.github.io" # the base hostname & protocol for your site
github_username:  pyromakesmusic

# Output destination
destination: ./_site


# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

