# Site settings
title: pyromakesmusic
email: pyromakesmusic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects and data analysis by pyromakesmusic.
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://pyromakesmusic.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  pyromakesmusic

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
